#!/bin/bash

# Statamic user configuration
cat >> /root/.bashrc <<EOM
chmod +x /opt/digitalocean/statamic_setup.sh
/opt/digitalocean/statamic_setup.sh
EOM

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
